# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MonoCli < Formula
  desc "Opinionated command line tool for managing all your project tasks."
  homepage "https://technikhil314.netlify.app/docs/mono-cli/introduction"
  version "0.0.0-alpha.11"
  license "MIT"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.11/mono-cli_0.0.0-alpha.11_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "918d8b0778a621295b3770c038070b1fc5d76c4c84fb95568c6dc42772d1ab35"

      def install
        bin.install "mono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.11/mono-cli_0.0.0-alpha.11_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9c2b81b858c5e8b11a342189efbbe15ef68378e4cb89df8137e3c3b54dd6442e"

      def install
        bin.install "mono"
      end
    end
  end
end
