# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MonoCli < Formula
  desc "Opinionated command line tool for managing all your project tasks."
  homepage "https://technikhil314.netlify.app/docs/mono-cli/introduction"
  version "0.0.0-alpha.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://www.github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.24/mono-cli_0.0.0-alpha.24_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b54e2da08f50baa6f138948d9afce7802815290c140dda3f9da607a4048c9e58"

      def install
        bin.install "mono"
      end
    end
    if Hardware::CPU.intel?
      url "https://www.github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.24/mono-cli_0.0.0-alpha.24_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "82069d610b029bbfdb6dc29db1058071bb0cc05c72201ebf78cf6d2a53ccb365"

      def install
        bin.install "mono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://www.github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.24/mono-cli_0.0.0-alpha.24_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c4aedf75ff6d1df9aa43f9de1e1738692e526f26b80517db04e27aa6dfa4301b"

      def install
        bin.install "mono"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://www.github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.24/mono-cli_0.0.0-alpha.24_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "da7038b22937d44a0561189dbaf0f54e5722dee96dd2fba65ad1f165cc77d495"

      def install
        bin.install "mono"
      end
    end
  end

  test do
    system "#{bin}/mono --version"
  end
end
