# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MonoCli < Formula
  desc "Opinionated command line tool for managing all your project tasks."
  homepage "https://technikhil314.netlify.app/docs/mono-cli/introduction"
  version "0.0.0-alpha.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.23/mono-cli_0.0.0-alpha.23_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "dbd05ba029418ded4bbbc6d442808f3b860c7043ff9de2750ea12d9da0682bdc"

      def install
        bin.install "mono"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.23/mono-cli_0.0.0-alpha.23_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "16618cf972bc9192d0ed596fd5df93c26c2a49c3946eedc21771bdbb3063b893"

      def install
        bin.install "mono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.23/mono-cli_0.0.0-alpha.23_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b59a2227ea5fac8ed6c8729182e9f161e1de9dd6eeb9f4b97cf43357482fca73"

      def install
        bin.install "mono"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/technikhil314/mono-cli/releases/download/v0.0.0-alpha.23/mono-cli_0.0.0-alpha.23_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8dd8542c500c1fd924db738939530684264d94c9a83c802dbf0a8e2258acb1c6"

      def install
        bin.install "mono"
      end
    end
  end

  test do
    system "#{bin}/mono --version"
  end
end
